services:
  amneziawg:
    build: ./src/tinyproxy
    container_name: amneziawg
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
    devices:
      - /dev/net/tun
    volumes:
      - ./awg0.conf:/etc/wireguard/awg0.conf
      - ./tinyproxy.conf:/etc/tinyproxy/tinyproxy.conf
    ports:
      - "8888:8888"               # <-- добавляем проброс порта прокси
    healthcheck:
      test: ["CMD", "awg", "show"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    command: awg0

  postgres:
    image: postgres:15-alpine
    container_name: manga-postgres
    restart: always
    environment:
      POSTGRES_DB: manga_day
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d manga_day"]
      interval: 10s
      timeout: 5s
      retries: 5

  pdf:
    build: ./src/manga-day/microservice/pdf
    container_name: manga-pdf 
    restart: always
    ports:
      - "3040:3040"
    environment:
      - PROXY=http://localhost:8888 # Если такового не имеется удалить environment
      - PORT=3040

    healthcheck:
      test: ["CMD-SHELL", "python", "health.py"]
      interval: 10s
      timeout: 10s
      retries: 5

  frontend:
    build: ./src/manga-day/src/frontend
    container_name: manga-frontend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - FRONTEND_HOST=0.0.0.0
      - FRONTEND_PORT=8000
      # - API_URL=http://192.168.0.50:8080
      - BACKEND_PORT=8080 # Что-бы узнать подробнее читать README.md `src/frontend/README.md`

    healthcheck:
      test: ["CMD-SHELL", "python", "health.py"]
      interval: 10s
      timeout: 10s
      retries: 5

  bot:
    build: ./src/manga-day/src/bot
    container_name: manga-bot
    restart: always
    environment:
      - ADMIN_BOT_TOKEN=1234567:QWERTYUIOP
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
      - ADMIN_IDS=12345,12346
      - USER_BOT_TOKEN=1234567:QWERTYUIOP
      - API_URL=http://localhost:8080
      - PDF_URL=http://localhost:3040
      - SITE_URL=http://192.168.0.50:8000
      - PROXY=http://localhost:8888

  app:
    build: ./src/manga-day
    container_name: manga-day-v1
    restart: always
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      amneziawg:
        condition: service_healthy
    volumes:
      - manga-day:/app/var
      - ./config.yaml:/app/config.yaml
    ports:
      - "8080:8080"

    healthcheck:
      test: ["CMD-SHELL", "python", "health.py"]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  manga-day:
  postgres_data:
